### ISSUE TITLE
Not able to mask regex.

### ISSUE THREAD

**Issue by rizvaughan** [fluent/fluent-plugin-sanitizer#2]
Hi, 
I am trying to sanitize a field in log using custom regex but I am not able to do it. According to the documentation, pattern_keywords is used to mask the found field with custom one provided in pattern_keywords. Secondly, it should only sanitize the found 'word' in the whole field and sanitize just that but in my case, it finds the work in the filed and sanitize the whole field instead of just the pattern_regex.
Here is my configuration
````
<filter **>
  @type sanitizer
  hash_salt mysalt
  <rule>
    keys uri
    pattern_regex /[0-9A-z-]+@[0-9A-z-]+\.[0-9A-z-]$/
    pattern_regex_prefix TEST
    pattern_keywords email
  </rule>
</filter>
````

Here is what I get in logs.
`[pattern_keywords] sanitize '/test/beladas@gyarabaje.com/test' to 'EMAIL_a83ed53c53be93c1746f8fea9daad1f2'`
I was expecting an output like : 
`[pattern_keywords] sanitize '/test/beladas@gyarabaje.com/test' to '/test/EMAIL_email/test'`.
Could someone tell me what am I doing wrong?
Thank you

**Comment by kubotat** [comment]
@rizvaughan I'm sorry for the late reply. I will look into it and get back to you.

**Comment by kubotat** [comment]
@rizvaughan 
With "pattern_regex" option, Sanitizer plugin mask whole field which matches given regular expression. 
Also, "pattern_keyword" works only when field completely matches specified keyword.   
I'm now developing new function to mask partial match with "capture group" as per your case like the following config. 
```
<filter demo>
  @type sanitizer
  @log_level debug
  hash_salt mysalt
  <rule>
    keys user.message
    pattern_regex /\/\w+\/(?<email>\w+\@\w+.\w+)\/\w+/
    regex_capture_group email
    pattern_regex_prefix EMAIL
  </rule>
</filter>
```
With the configuration above, input like "/test/beladas@gyarabaje.com/test" will be masked like:
```
2021-07-12 18:00:29 +0000 [debug]: #0 [pattern_regex] sanitize '/test/test@test.com/test' to '/test/EMAIL_6f5d4443c5fd2649c59d6f3f733d1761/test'
```
Does this work for your case? If it works for you, I will merge new function.

**Comment by rizvaughan** [comment]
Hi @kubotat ,
First of all thank you for help. It's really appreciated. 
I tried your given config but unfortunately, the result is the same for me. With the config 
````
<filter **>
  @type sanitizer
  @log_level debug
  hash_salt mysalt
  <rule>
    keys uri
    pattern_regex /\/\w+\/(?<email>\w+\@\w+.\w+)\/\w+/
    regex_capture_group email
    pattern_regex_prefix EMAIL
  </rule>
</filter>
````
I still get 
`2021-07-12 21:10:57 +0000 [debug]: #0 [pattern_keywords] sanitize '/test/beladas@gyarabaje.com/test' to 'EMAIL_a83ed53c53be93c1746f8fea9daad1f2'`

**Comment by kubotat** [comment]
@rizvaughan I did not merge new code yet. Will let you know once I merged code.

**Comment by rizvaughan** [comment]
> @rizvaughan I did not merge new code yet. Will let you know once I merged code.

aah sorry, I misunderstood. Yes, that's what I want.
Thank you

**Comment by kubotat** [comment]
@rizvaughan I merged the code and uploaded new gem as v0.1.2. Could you please install plugin again and try the following configuration out?
```
<filter **>
  @type sanitizer
  @log_level debug
  hash_salt mysalt
  <rule>
    keys uri
    pattern_regex /\/\w+\/(?<email>\w+\@\w+.\w+)\/\w+/
    regex_capture_group email
    pattern_regex_prefix EMAIL
  </rule>
</filter>
```

**Comment by rizvaughan** [comment]
Hi @kubotat ,
Now it works like a charm!
It is exactly what I needed.
`/test/EMAIL_f648327f8cb2d7d6774cd6be0f4b92b4/test`
or
`[pattern_regex] sanitize '/test1/test2/beladas@gyarabaje.com/test/something' to '/test1/test2/EMAIL_f648327f8cb2d7d6774cd6be0f4b92b4/test/something'`
Thank you very much for your help!

**Comment by kubotat** [comment]
@rizvaughan Great to hear that. If you have any question or other use cases which sanitizer plugin does not work, please let us know.
