### ISSUE TITLE
Support for better hashing algorithms

### ISSUE THREAD

**Issue by f9-abs** [fluent/fluent-plugin-sanitizer#7]
Looking at the code, I understand currently this plugin uses MD5 as the hashing algorithm. Is there a plan to support more secure hashing algorithms (e.g. SHA-256/512)?

**Comment by jlangford9284** [comment]
I would also like to see this!

**Comment by kubotat** [comment]
@f9-abs @jlangford9284 Sorry for the late reply. I just merged PR which include new `hash_scheme` option and upload new gem version 0.1.3 in rubygem. If you have any issue, please let me know. Thanks.
