### ISSUE TITLE
Hash Salt is not Optional

### ISSUE THREAD

**Issue by moritzploss-k** [fluent/fluent-plugin-sanitizer#8]
Thanks for this great plugin!

I noticed that if I don't explictly specify a `hash_salt`, the plugin produces an error. However, according to the README, providing a hash salt is optional. This is my configuration:

```
<filter **>
  @type sanitizer
  <rule>
    keys query.ssn
    pattern_regex /^.*$/
    pattern_regex_prefix REDACTED
  </rule>
</filter>
```

And I get this error:

```
2022-02-14 09:45:10 +0000 [warn]: #0 dump an error event: error_class=NoMethodError error="undefined method `+' for nil:NilClass" location="/usr/lib/ruby/gems/2.7.0/gems/fluent-plugin-sanitizer-0.1.2/lib/fluent/plugin/filter_sanitizer.rb:164:in `sanitize_regex'" tag="my_tag" record={"query"=>{"ssn"=>["123"]}}
```

If I change my configuration and provide a `hash_salt`, the error disappears and it works as expected:

```
<filter **>
  @type sanitizer
  hash_salt mysalt
  <rule>
    keys query.ssn
    pattern_regex /^.*$/
    pattern_regex_prefix REDACTED
  </rule>
</filter>
```

**Comment by kubotat** [comment]
@moritzploss-k I'm sorry for the very late reply. I just made changes and upload new gem v0.1.3. I would appreciate it if you could try new gem out in your environment:) Thanks.
